//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_SUPPLIER
    {
        public int PRODUCT_SUPPLIER_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
